In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
a = np.arange(1,101)
b = np.arange(501,600)

### Split the Data

In [12]:
train_test_split(a)

[array([ 26,   5,  10,  94,  35,  87,  81,  63,  68,  97,  92,  32,  52,
         64,  91,  17,   3,  79,  55,  16,   8,  19,  36,  75,  42,  95,
         60,  58,   2,  41,   6,  82,  43,  56,  89,  14,  18,  37,  69,
         12,  70,  23,  62,  48,  65,  44,  40,  15,  45,   7,  77,  30,
         57,  83,  96,  84,  88, 100,  99,  98,  11,  53,  13,  86,  47,
         46,  66,  90,  34,  78,  38,  31,  28,  25,  59]),
 array([73, 74,  4, 61, 49, 33, 21, 22, 80, 54, 20, 24, 72, 67, 50, 93,  9,
        51, 29, 27, 76, 71,  1, 39, 85])]

In [58]:
# Assuming a and b are your datasets
# Check the lengths of a and b
if len(a) != len(b):
    # Adjust a or b to have the same number of samples
    # For example, if b has fewer samples, you can truncate a
    min_length = min(len(a), len(b))
    a = a[:min_length]  # Truncate a to match the length of b
    b = b[:min_length]  # Or truncate b to match the length of a

# Now both a and b have the same number of samples
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)

In [60]:
a_train.shape, a_test.shape

((79,), (20,))

In [62]:
a_train

array([50, 71, 69, 16, 40, 34, 10, 82, 12, 66, 95, 31, 29, 90,  6, 46, 70,
       36, 17, 73, 35,  8, 56, 28, 20, 81, 26, 54, 14, 25,  4, 18, 39,  9,
       78,  7, 80, 37, 92, 57, 99, 55, 44, 51, 67, 47, 68, 62, 97, 79, 42,
       59, 49, 86, 58, 76, 33, 94, 60, 64, 84, 38, 30,  2, 53, 22,  3, 24,
       88, 91, 75, 87, 83, 21, 61, 72, 15, 93, 52])

In [64]:
a_test

array([63, 41, 96, 19, 98, 85, 65, 43, 11,  1, 32, 77, 48, 27, 45,  5, 23,
       13, 89, 74])

In [66]:
b_train

array([550, 571, 569, 516, 540, 534, 510, 582, 512, 566, 595, 531, 529,
       590, 506, 546, 570, 536, 517, 573, 535, 508, 556, 528, 520, 581,
       526, 554, 514, 525, 504, 518, 539, 509, 578, 507, 580, 537, 592,
       557, 599, 555, 544, 551, 567, 547, 568, 562, 597, 579, 542, 559,
       549, 586, 558, 576, 533, 594, 560, 564, 584, 538, 530, 502, 553,
       522, 503, 524, 588, 591, 575, 587, 583, 521, 561, 572, 515, 593,
       552])

In [68]:
b_test

array([563, 541, 596, 519, 598, 585, 565, 543, 511, 501, 532, 577, 548,
       527, 545, 505, 523, 513, 589, 574])